# https://www.practicepython.org/exercise/2014/07/05/18-cows-and-bulls.html
# Create a program that will play the “cows and bulls” game with the user. 
# The game works like this:

# Randomly generate a 4-digit number. 
# Ask the user to guess a 4-digit number. 
# For every digit that the user guessed correctly in the correct place, they have a “cow”. 
# For every digit the user guessed correctly in the wrong place is a “bull.” 
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
# Once the user guesses the correct number, the game is over. 
# Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...

# Until the user guesses the number.

from random import randrange


def main():
    print("Welcome the cows and bulls game! Guess a 4 digit number. Every correct digit in the correct place will be a cow and every correct digit in the wrong place will be a bull. ")

    generated_num: int = randrange(1000, 9999)
    generated_num_str: str = str(generated_num)
    guess_count = 0

    _done: bool = False
    while not _done:
        try:
            echo: str = input("enter a 4 digit number:")
        except Exception as e:
            print(f"error: {e}")
            continue
        if len(echo) != 4:
            print(f"{echo} does not have the correct number of characters")
            continue
        try:
            int(echo)
        except ValueError as e:
            print(f"error: {e} - {echo} does not seem to contain only digits")
            continue

        cow_count: int = 0
        bull_count: int = 0
        for x in range(len(echo)):
            if generated_num_str[x] == echo[x]:
                cow_count += 1
            elif echo[x] in generated_num_str:
                bull_count += 1

        cow_str = "cows"
        bull_str = "bulls"
        if cow_count == 1:
            cow_str = "cow"
        elif cow_count == 4:
            print(f"Congradulations it took {guess_count} to find all 4 cows!")
            _done = True
            break
        if bull_count == 1:
            bull_str = "bull"

        guess_count += 1
        print(f"{cow_count} {cow_str}, {bull_count} {bull_str}, {guess_count} guesses")


if __name__ == "__main__":
    main()
